### ISSUE TITLE
exports is not definied using @storybook/testing-library

### ISSUE THREAD

**Issue by drianoaz** [Karibash/storybook-addon-swc#20]
Hi,

I have a storybook with some components that make use of [Stortybook's play function](https://storybook.js.org/docs/react/writing-stories/play-function) and they stopped working after I set it up the `storybook-addon-swc` in the project.

When I open the storybook in the browser, the following error message is being displayed

![image](https://user-images.githubusercontent.com/15058771/160417323-4012682b-9203-432d-8c03-9e4269c21067.png)

When I disable the `enableSwcLoader` setting, the Storybook works again.

Why does it happen? is an expected behavior?

Is it possible to do something to keep using `enableSwcMinify` enabled? The storybook build happens faster when we use it

---

Here is my configuration:

```javascript
const path = require('path');
const { StorybookFrontLoaderPlugin } = require('./storybookFrontLoaderPlugin');

module.exports = {
  stories: ['../**/*.stories.mdx', '../**/*.stories.@(js|jsx|ts|tsx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-a11y',
    '@storybook/addon-interactions',
    'storybook-addon-next-router',

    // this will give error
    'storybook-addon-swc',

    // this will work
    // {
    //   name: 'storybook-addon-swc',
    //   options: {
    //     enableSwcLoader: false,
    //   },
    // },
  ],
  framework: '@storybook/react',
  core: {
    builder: 'webpack5',
  },
  staticDirs: ['../public'],
};
```

Here is a example story:

```tsx
// MyComponent.stories.tsx
import { ComponentStory } from '@storybook/react';
import { userEvent, within } from '@storybook/testing-library';

export default {
  title: 'MyComponent',
};

const Component = () => {
  return <input type="text" placeholder="Search..." />;
};

const Template: ComponentStory<typeof Component> = () => {
  return <Component />;
};

export const Main = Template.bind({});

Main.play = async ({ canvasElement }) => {
  const canvas = within(canvasElement);

  const input = canvas.getByPlaceholderText('Search...');

  await userEvent.type(input, 'Foo bar', {
    delay: 100,
  });
};
```

**Comment by Karibash** [comment]
@drianoaz 
Thank you for reporting the issue.
I was able to build successfully by setting the [isModule property to unknown](https://github.com/Karibash/storybook-addon-swc/pull/27/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R22).
Please check [v1.1.6](https://github.com/Karibash/storybook-addon-swc/releases/tag/v1.1.6) for the fix.

**Comment by drianoaz** [comment]
@Karibash the fix you released solved the problem. Because of this I'll close this issue, ok?

Thanks so much for the help 🙏
