### ISSUE TITLE
Missing webpack dep in example project package.json files

### ISSUE THREAD

**Issue by kylemh** [Karibash/storybook-addon-swc#22]
https://github.com/Karibash/storybook-addon-swc/blob/main/examples/webpack4/package.json
https://github.com/Karibash/storybook-addon-swc/blob/main/examples/webpack5/package.json

The relevant webpack version should be listed... At least for Webpack 5. Without it, you run into [this issue](https://github.com/storybookjs/storybook/issues/15336).

**Comment by Karibash** [comment]
@kylemh 
Thank you for reporting the issue.
I have fixed the issue in the following PR.
#23
