### ISSUE TITLE
Breaking change in recent version

### ISSUE THREAD

**Issue by lesha1201** [Karibash/storybook-addon-swc#32]
Hello! I've recently tried to upgrade from version `1.1.1` to `1.1.7` and the build were failing with error `Error: failed to handle: not implemented: automatic polyfill for scripts`:

![image](https://user-images.githubusercontent.com/10157660/164489499-997246b7-cd0b-4d41-83b8-c64b754e5280.png)

I noticed that `isModule` were changed to `isModule: 'unknown'` in this commit ed714baecdb02df7efaebdeb8da4ef47d74c1e50. Changing it back to the default value `isModule: true` fixes it.

I don't know why it doesn't work with `isModule: 'unknown'` but letting you know about this issue and how it can be fixed if someone encounters it.

**Info:**
- Storybook 6.4.19
- React 17.0.2
- TypeScript 4.6.2
- @swc/core 1.2.170

**Swc config:**
```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": false,
      "dynamicImport": false
    },
    "loose": true
  },
  "env": {
    "targets": "> 0.5%, last 2 versions, Firefox ESR, not dead, not ie <= 11"
  }
}
```

**Comment by Karibash** [comment]
@lesha1201 
Thank you for reporting the issue.

The relevant error seems to occur when going through the following process.
https://github.com/swc-project/swc/blob/747b8a188929b7f24b16f3b733d83909b424c948/crates/swc_ecma_preset_env/src/lib.rs#L447-L449

However, I don't have much knowledge of Rust, so I am not sure why this process is being executed.
It might be a problem on the SWC side, so it might be better to submit an issue in the SWC repository.

I will close this issue for now and re-open it if many others seem to encounter the same error.

**Comment by salamaashoush** [comment]
I have the same issue after upgrading from `1.1.5` to `1.1.7` if I downgrade it works fine, so I guess it might be something related to the addon not swc since I use latest swc in both cases, also after adding `isModule:true` it works fine with `1.1.7`

**Comment by AleksandarDev** [comment]
We are experiencing same issue with 1.1.7 addon, seems to work fine with latest swc and loader with 1.1.5 addon

Not working:

```json
    "@swc/core": "1.2.203",
    "storybook-addon-swc": "1.1.7",
    "swc-loader": "0.2.3",
```

Working:

```json
    "@swc/core": "1.2.203",
    "storybook-addon-swc": "1.1.5",
    "swc-loader": "0.2.3",
```

`.swcrc`:

```json
{
  "env": {
    "targets": {
      "chrome": "90"
    }
  },
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": true
    },
    "target": "es2020"
  },
  "minify": true
}
```

**Comment by bes** [comment]
Same thing with `1.1.8`, downgrading to `1.1.5` helps. I can add more information if needed @Karibash 

EDIT: I fixed it by configuring `isModule: true` as suggested in the original post:

```javascript
        {
            name: "storybook-addon-swc",
            options: {
                swcLoaderOptions: {
                    isModule: true, // This fixed my build
                    module: {
                        // Our storybook build needs commonjs, otherwise it won't compile properly.
                        // NOTE: Other GitHub users reading this might not need it.
                        type: "commonjs",
                    },
                },
            },
        },
```

**Comment by Karibash** [comment]
The small number of people encountering the same problem makes me wonder if the swc settings of the person using it are simply incorrect.
I have pinned this issue so that others encountering the same glitch can find a solution.

By the way, the default value of isModule is false, not true.
https://swc.rs/docs/configuration/compilation#:~:text=false%0A%20%20%7D%2C-,%22isModule%22%3A%20false,-%7D
