### ISSUE TITLE
Broken dependencies

### ISSUE THREAD

**Issue by protiumx** [Karibash/storybook-addon-swc#33]
Hi there. I was just trying out this plugin but it seems some dependencies are broken.
Any possible fix?
![image](https://user-images.githubusercontent.com/43855513/171595425-198a7ce1-c8d7-420a-ad0f-b1235969be8f.png)

Cheers

**Comment by Karibash** [comment]
@protiumx
Thank you for reporting the issue.

This seems to be a problem on the storybook side.
https://github.com/storybookjs/storybook/issues/15252

If you are using yarn, you may be able to resolve dependencies by using the resolutions field.
https://github.com/storybookjs/storybook/issues/15252#issuecomment-870987424
(If you are using npm, the resolutions field is not supported, so you must use [npm-force-resolutions](https://github.com/rogeriochaves/npm-force-resolutions).)

**Comment by jsamr** [comment]
> (If you are using npm, the resolutions field is not supported, so you must use [npm-force-resolutions](https://github.com/rogeriochaves/npm-force-resolutions).)

FWY since I was passing by, npm since version 8.3.0 supports an equivalent feature [with the "overrides" field](https://stackoverflow.com/a/70396201/2779871).
