### ISSUE TITLE
Optional dependency should not be statically imported

### ISSUE THREAD

**Issue by HosseinAgha** [Karibash/storybook-addon-swc#38]
Please check https://github.com/Karibash/storybook-addon-swc/blob/e8f97e564b965f6545c48cbe4c16077cfbee0b11/src/transformers.ts#L3   

IMHO, as `terser-webpack-plugin` is a optional peer dependency you should dynamically require it only when we use terser for minification.

**Comment by Karibash** [comment]
@HosseinAgha 
Thank you for reporting the issue.

Thank you for your report.
I corrected the problem in the following PR.
https://github.com/Karibash/storybook-addon-swc/pull/39

The fix is applied from [v1.1.8](https://github.com/Karibash/storybook-addon-swc/releases/tag/v1.1.8).
