### ISSUE TITLE
Addon results in webpack RuleSetCompiler.error when used with @nx/webpack

### ISSUE THREAD

**Issue by R-J-dev** [Karibash/storybook-addon-swc#52]
Hi @Karibash,

Not sure if I have to report it here or at NX, but I recently updated to a new NX webpack version (@nx/webpack) and there seems to occur an error with the storybook-addon-swc. You can find the error below and I also have made a basic reproduction repo here: https://github.com/R-J-dev/storybook-swc-example. When patching your addon by simply setting the babel rule options to undefined, it started to work again. 

May I ask why the babel options are currently preserved and not being set to undefined and/or replaced by the SWC options? If the babel options aren't needed, I am happy to create a PR to set the options to undefined.

Thanks in advance and I hope to hear what your point of view is on this.

The error is: `Error: Compiling RuleSet failed: A Rule must not have a 'options' property when it has a 'use' property (at ruleSet[1].rules[11].options: [object Object])`

**Comment by Karibash** [comment]
Hi, @R-J-dev 
Sorry it took me so long to reply.
I think you should use the latest version of Storybook, which allows you to use [SWC without the need for addons](https://storybook.js.org/docs/api/main-config-swc), etc.
I plan to deprecate storybook-addon-swc in the future.

**Comment by R-J-dev** [comment]
@Karibash no problem and thanks for replying!
I tried what you suggested already, but just to be sure once again in this branch: https://github.com/R-J-dev/storybook-swc-example/tree/example/storybook-swc-without-addon.

It's still looking for a `.babelrc` file according to the following error:
Error: Cannot find module './.babelrc'

When looking at the source code of your addon, I was under the impression that Storybook uses a babel loader by default. But I guess that the problem is in NX or my setup, so I will close this issue.

**Comment by newsiberian** [comment]
@R-J-dev did you find a solution?

**Comment by R-J-dev** [comment]
@newsiberian as a temporary fix, I overwrite the babel-loader in the webpackFinal configuration element in the .storybook/main.js|ts file. But I think that the actual bug is the same as described here: https://github.com/nrwl/nx/issues/21767.

Assuming that you use NX as well. It might be fixed already when you update to the latest version of NX and Storybook. But I haven't tested it yet.

**Comment by newsiberian** [comment]
@R-J-dev , thanks! I've managed to fix the issue yesterday by adding `"compiler": "swc",` to NX config related to storybook-build, but now I want to go further and migrate from `'@storybook/react-webpack5'` to `'@storybook/nextjs'`. My current issue there is that compiler doesn't transpile TS files from within `node_modules`.... by default. And yah... I'm still on the latest NX@17
